### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by harrykamboj1** [harrykamboj1/DataStructureAndAlgorithms#1]
1. Introduction regarding the current repository

**Comment by bhavnagarg12ja** [comment]
@harrykamboj1 Please add the description

**Comment by harrykamboj1** [comment]
@bhavnagarg12ja discription added , Plz Check

**Comment by bhavnagarg12ja** [comment]
@harrykamboj1 Kindly check. Enhancement done
